name = "Baja Isles"
author = "Wesley"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "743d58ea9c327cabbf0b8dedb0b8164a4961c78381f64cd2bd2617d58bd1508b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
