name = "Baja Isles"
author = "Wesley"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06a3c9be985bb44954a9b9ada1c91d1f9fdf05d70210ff4d2cb17b4889fdc105"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
