name = "Baja Isles"
author = "Wesley"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f3b1545545f37c26fb68cf71dcb92fc288f6a2a08de30e448dd25e120e2fc752"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
